AllCops:
  Exclude:
    - "bin/**/*"
    - "gemfiles/**/*"
    - "vendor/**/*"
    - "Gemfile"
    - "Rakefile"
    - "*.gemspec"
    - "config.ru"

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/ClassCheck:
  EnforcedStyle: kind_of?

Metrics/LineLength:
  Max: 80

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Proc:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Layout/DotPosition:
  EnforcedStyle: leading

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Style/DoubleNegation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%":  "[]"
    "%i": "[]"
    "%q": "[]"
    "%Q": "[]"
    "%r": "[]"
    "%s": "[]"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Style/CollectionMethods:
  PreferredMethods:
    collect: "map"
    collect!: "map!"
    inject: "reduce"
    detect: "find"
    find_all: "select"

Style/SafeNavigation:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false
